# Generated by Django 4.2.4 on 2023-08-24 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches_player1', to='player.player', verbose_name='Jugador 1')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches_player2', to='player.player', verbose_name='Jugador 2')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches_winner', to='player.player', verbose_name='Ganador')),
            ],
            options={
                'verbose_name': 'Encuentro',
                'verbose_name_plural': 'Encuentros',
            },
        ),
        migrations.CreateModel(
            name='BoardGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options_player1', models.TextField(max_length=254)),
                ('options_player2', models.TextField(max_length=254)),
                ('options_totals', models.TextField(max_length=254)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boardgame_player1', to='player.player', verbose_name='Jugador 1')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boardgame_player2', to='player.player', verbose_name='Jugador 2')),
                ('player_turn', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boardgame_player_turn', to='player.player', verbose_name='Jugador 2')),
            ],
        ),
    ]
