# Generated by Django 4.2.4 on 2023-08-25 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_alter_boardgame_player_turn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardgame',
            options={'verbose_name': 'Tablero'},
        ),
    ]
